### ISSUE TITLE
Can't run (image mydomain/aegir_maria:latest not found)

### ISSUE THREAD

**Issue by drupol** [DominicBoettger/docker-aegir-mariadb#2]
Hello,

I have this error when trying to start the docker:

pol@x230 ~/git/docker-aegir-mariadb $ docker run -d -v /var/docker/aegir01/usr/share/solr4:/usr/share/solr4 -v /var/docker/aegir01/var/aegir:/var/aegir -v /var/docker/aegir01/var/log/apache2:/var/log/apache2 -v /var/docker/aegir01/var/lib/mysql:/var/lib/mysql -v /var/docker/aegir01/etc/mysql/conf.d:/etc/mysql/conf.d -v /var/docker/aegir01/var/log/mysql:/var/log/mysql -e POSTFIX_MAILNAME=aegir01.mydomain.com -e POSTFIX_DESTINATION=aegir01.mydomain.com -e AEGIR_SITE=aegir01 -e AEGIR_FRONTEND_URL=aegir01.mydomain.com -e AEGIR_EMAIL=aegir01@mydomain.com -e AEGIR_DB_PASSWORD=CHANGEME -e AEGIR_VERSION=6.x-2.0-rc5 -e MYSQL_ROOT_PW=CHANGEME -e SOLR_PASS=CHANGEME -e SOLR_VERSION=4.6.0 -p 30880:8080 -p 30080:80 -p 30443:443 -p 30022:22 -h aegir01 -name aegir01 mydomain/aegir_maria
Warning: '-name' is deprecated, it will be replaced by '--name' soon. See usage.
Unable to find image 'mydomain/aegir_maria:latest' locally
Pulling repository mydomain/aegir_maria
FATA[0001] Error: image mydomain/aegir_maria:latest not found

What should I do to fix that ?

Thanks.

**Comment by DominicBoettger** [comment]
Hi,

you replaced the Image Name Inspirationlabs/aegir_maria with
mydomain/aegir_maria.

Best regards
Dominic

Am Dienstag, 3. März 2015 schrieb Pol Dellaiera :

> Hello,
> 
> I have this error when trying to start the docker:
> 
> pol@x230 ~/git/docker-aegir-mariadb $ docker run -d -v
> /var/docker/aegir01/usr/share/solr4:/usr/share/solr4 -v
> /var/docker/aegir01/var/aegir:/var/aegir -v
> /var/docker/aegir01/var/log/apache2:/var/log/apache2 -v
> /var/docker/aegir01/var/lib/mysql:/var/lib/mysql -v
> /var/docker/aegir01/etc/mysql/conf.d:/etc/mysql/conf.d -v
> /var/docker/aegir01/var/log/mysql:/var/log/mysql -e POSTFIX_MAILNAME=
> aegir01.mydomain.com -e POSTFIX_DESTINATION=aegir01.mydomain.com -e
> AEGIR_SITE=aegir01 -e AEGIR_FRONTEND_URL=aegir01.mydomain.com -e
> AEGIR_EMAIL=aegir01@mydomain.com
> <javascript:_e(%7B%7D,'cvml','aegir01@mydomain.com');> -e
> AEGIR_DB_PASSWORD=CHANGEME -e AEGIR_VERSION=6.x-2.0-rc5 -e
> MYSQL_ROOT_PW=CHANGEME -e SOLR_PASS=CHANGEME -e SOLR_VERSION=4.6.0 -p
> 30880:8080 -p 30080:80 -p 30443:443 -p 30022:22 -h aegir01 -name aegir01
> mydomain/aegir_maria
> Warning: '-name' is deprecated, it will be replaced by '--name' soon. See
> usage.
> Unable to find image 'mydomain/aegir_maria:latest' locally
> Pulling repository mydomain/aegir_maria
> FATA[0001] Error: image mydomain/aegir_maria:latest not found
> 
> What should I do to fix that ?
> 
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DominicBoettger/docker-aegir-mariadb/issues/2.

## 

Dominic Böttger

Dominic.Boettger@inspirationlabs.com

---

INSPIRATIONlabs GmbH

Rohrbacher Str. 79 | D-69115 Heidelberg | Germany
Tel. +49-6221-9853-680

inspirationlabs.com

Sitz der Gesellschaft: Heidelberg
Handelsregister: Amtsgericht Mannheim, HRB 704782

**Comment by drupol** [comment]
It works if you use this:

docker run -d -v /var/docker/aegir01/usr/share/solr4:/usr/share/solr4 -v /var/docker/aegir01/var/aegir:/var/aegir -v /var/docker/aegir01/var/log/apache2:/var/log/apache2 -v /var/docker/aegir01/var/lib/mysql:/var/lib/mysql -v /var/docker/aegir01/etc/mysql/conf.d:/etc/mysql/conf.d -v /var/docker/aegir01/var/log/mysql:/var/log/mysql -e POSTFIX_MAILNAME=aegir01.mydomain.com -e POSTFIX_DESTINATION=aegir01.mydomain.com -e AEGIR_SITE=aegir01 -e AEGIR_FRONTEND_URL=aegir01.mydomain.com -e AEGIR_EMAIL=aegir01@mydomain.com -e AEGIR_DB_PASSWORD=CHANGEME -e AEGIR_VERSION=6.x-2.0-rc5 -e MYSQL_ROOT_PW=CHANGEME -e SOLR_PASS=CHANGEME -e SOLR_VERSION=4.6.0 -p 30880:8080 -p 30080:80 -p 30443:443 -p 30022:22 -h aegir01 --name aegir01 inspirationlabs/docker-mariadb-galera

Can you update the readme file maybe ?
