### ISSUE TITLE
Aegir impossible to install (Drush was not able to start (bootstrap) the Drupal database.)

### ISSUE THREAD

**Issue by drupol** [DominicBoettger/docker-aegir-mariadb#3]
Hello Dominic, Helmo,

To learn Docker, I've tested both of your repositories and try to run a working Aegir.
To train myself a bit, I've structured the repository files.
You can find my work here: https://github.com/Polzme/docker-aegir-mariadb

Right now, everything is working except the Aegir installation. It fails at a certain point with this error.
You can review the whole log from ./run.sh in the container here: http://pastebin.com/RrV6GfDW

To reproduce the error,

Start: ./Docker_build.sh
Then: ./Docker_run.sh
Then: ./run.sh

Do you think the problem is coming from the installation script or Aegir ?

Thanks.

**Comment by DominicBoettger** [comment]
I think there is a issue with the permissions. I think aegir is not installed correctly, but i am not sure why the installation script fails. Sorry, i did not try to install this version of aegir yet.... Did you ask @Helmo if he has any idea about the issues with this version?

**Comment by drupol** [comment]
It fails with aegir 6.x too, same error.

**Comment by drupol** [comment]
About Helmo, not yet asked.

**Comment by DominicBoettger** [comment]
I think this can be your problem: http://community.aegirproject.org/installing/manual#DNS_configuration

**Comment by drupol** [comment]
I tried, no luck :(

I'm trying to find where it fails, it's not easy to debug this thing.

**Comment by helmo** [comment]
It's been a while since I've worked with this. But from what I remember I had trouble with sudo.

Aegir uses sudo to reload apache, but Docker does not allow sudo.
