### ISSUE TITLE
Installing Drush with PEAR deprecated (not working anymore)

### ISSUE THREAD

**Issue by mjroeleveld** [DominicBoettger/docker-aegir-mariadb#4]
Since a few days, `pear.drush.org` doesn't resolve to an ip address. Apparently Drush now can't be installed via PEAR anymore and it should be installed via Composer or as described [here](http://docs.drush.org/en/master/install/). See [this issue](https://www.drupal.org/node/1322564) which has been reopened since.

**Comment by DominicBoettger** [comment]
Will you be able to create a pull request?
